### PR TITLE
Migrate to pyproject.toml and poetry [RHELDST-15226]

### PR DESCRIPTION
**Pull request by negillett**
This commit replaces setup.py and requirements files with pyproject.toml and implements poetry for dependency management in CI.

### CODE REVIEW

**Comment by negillett** [comment]
@rohanpm, is there any way to disable the virtualenv used by pidiff? I suspect that has something to do with the installation failure during that check.

**Comment by negillett** [comment]
Having some trouble with this repo and it takes a while to solve deps and rewrite poetry.lock due to py36 so a solve is taking longer

**Comment by negillett** [comment]
@rbikar, @drepelov, this is ready for review. Note coverage fails due to upload rate limit, cov itself passed.

**Comment by negillett** [comment]
Updated release workflow to use poetry build and publish

**Comment by negillett** [comment]
ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1569s.', code='throttled')

**Review by rbikar — APPROVED** [review]

**Pull request merged**
