### PR TITLE
ci: Add Code Climate support

### PR DESCRIPTION
**Pull request by litleleprikon**
Add Code Climate badge to `README.md`. Add `.codeclimate.yml`
configuration file. This config file add following checks:

* shellcheck
* bandit
* markdownlint
* pep8

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
@litleleprikon who is the owner of code climate account?

**Comment by litleleprikon** [comment]
@alexandrevicenzi codeclimate connects to your GitHub account and gives access for your repos and your organization repos, so everyone of our organization have access for this repo settings

**Comment by alexandrevicenzi** [comment]
@litleleprikon I think we should have a global code climate account, like the one for Travis or Pypi. Just to keep this in mind, I don't want to create a code climate account just for this report.

**Comment by litleleprikon** [comment]
@alexandrevicenzi we do not need to create the account because code climate works with GitHub access rights and everyone in our team have access to this project in codeclimate

**Pull request merged**
